### ISSUE TITLE
Docs around using `import_fn` and`host_fn`

### ISSUE THREAD

**Issue by fliepeltje** [extism/python-pdk#26]
As I understand it, you use `import_fn` to defer some operation from a plugin to the host by means of defining a `host_fn`, but I cannot seem to get this to work - I'd love to experiment a bit more with this and I'd really appreciate some docs or an example that combines the use of `import_fn` and `host_fn` - the way I imagine this to work:

plugin code:
```python
import extism

@extism.import_fn("app", "some_host_op")
def some_host_op(): ...

@extism.plugin_fn
def some_fn():
    some_host_op()
```

app code:
```python
import extism

@extism.host_fn
def some_host_op():
    print("...")

manifest = ...
with extism.Plugin(manifest, wasi=True) as plugin:
    plugin.call("some_fn", "")
```

**Comment by zshipko** [comment]
Thanks, I will add an issue to improve docs for decorators.

It looks like your example above would work if you switch `import_fn` to `import_fn("extism:host/user","some_host_op")` instead.
