### ISSUE TITLE
Python2wasm compilers

### ISSUE THREAD

**Issue by psychemedia** [extism/python-pdk#3]
I note a couple of possibly relevant recent releases for compiling Python to WASM:

- `cibuildwheel` support for pyodide/wasm: https://github.com/pypa/cibuildwheel/pull/1456
- `py2wasm` - https://wasmer.io/posts/py2wasm-a-python-to-wasm-compiler https://github.com/Nuitka/Nuitka/pull/2814

**Comment by G4Vi** [comment]
Thanks for the links! When we eventually get back to making a python pdk we'll consider those options.

**Comment by bhelx** [comment]
Thank you! These are certainly options and i've got some interest in py2wasm. let's move the convo to #2
