### ISSUE TITLE
config example is raising a wasm error

### ISSUE THREAD

**Issue by fliepeltje** [extism/python-pdk#31]
I'm getting the following output when running the configs example from the readme:

```output
Error: wasm error: unreachable
wasm stack trace:
        .$10486(i32,i32,i32,i32,i32)
        .$10772(i32,i32)
        .$10792(i32,i32,i32,i32,i32)
        .$10827(i32,i32) i32
        .$10846() i32
returned non-zero exit code: 1
```

I figured out that it is because it should in fact be a `get_str` call:

```py
import extism

@extism.plugin_fn
def greet():
  user = extism.Config.get_str("user")
  extism.output_str(f"Hello, {user}!")
```

But I find the output of this mistake quite scary; I'm unsure if it is somehow possible to throw up something a bit friendlier when you try to access a non-existent method or var?

**Comment by bhelx** [comment]
> I figured out that it is because it should in fact be a get_str call:

do you have an example of the broken program? Maybe we are not handling an error condition properly.

> But I find the output of this mistake quite scary; I'm unsure if it is somehow possible to throw up something a bit friendlier when you try to access a non-existent method or var?

`unreachable` is kind of the equivalent of a segfault. Sometimes it can be tricky to get context to show the user. the numbers are because, i assume, the python implementation is compiled without debug info. Maybe we can compile it with the debug info? @zshipko should know.

**Comment by fliepeltje** [comment]
> do you have an example of the broken program

It is literally the [docs example](https://github.com/extism/python-pdk?tab=readme-ov-file#configs) - I'll make a PR for it.

> using the EXTISM_ENABLE_WASI_OUTPUT environment variable

This does indeed give more info, for now that is all I need :) 

In the PR for this I will also incorporate this nugget of knowledge into the readme :)
