### ISSUE TITLE
Make it possible to specify host functions from the Python source

### ISSUE THREAD

**Issue by zshipko** [extism/python-pdk#4]
Python doesn't have a clear way to specify these, I am considering a couple different approaches:

- Python decorator 
```
@extism.import("extism:host/env", "my_func")
def my_func(x: str) -> str:
    pass
```

- Import comments, something like 
```
# import: extism:host/env my_func
def my_func(x: str) -> str:
    pass
```

- Putting imports into a separate JSON file - this is not a great option since it makes imports appear out of nowhere in the source

I'm currently leaning toward using a decorator since it seems like the cleanest integration, and should be pretty easy to parse.

**Comment by nilslice** [comment]
without much more context on the subject beyond what you've shared, I think the decorator sounds good, particularly since it's also how we (optionally?) declare host functions from the Python SDK
